# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/pgxmldbgui

LANGUAGE = C++
SOURCES += pgxmldbgui.cpp \
           main.cpp 
HEADERS += pgxmldbgui.h 
TEMPLATE = app 
CONFIG += release \
          warn_on \
          qt \
          thread 
TARGET = ../bin/pgxmldbgui 
unix{
  LIBS += -lqassistantclient
  MOC_DIR += ./.moc
  OBJECTS_DIR += ./.obj
  UI_DIR += ./.ui
}
